spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Qwerty@123
    url: jdbc:mysql://localhost:3306/irctcdata
    username: root
  application:
   name: irctc-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  springdoc:
   swagger-ui:
      path: swagger-ui.html
#    //path: swagger-ui.html   //http://localhost:8080/swagger-ui/index.html

